In [6]:
import torch

In [5]:
def activation(x):
    """Sigmoid activation function.

    Arguments:
    ---------
    x: torch.Tensor
    """
    return 1 / (1 + torch.exp(-x))

In [7]:
### Generate some data.
torch.manual_seed(7)  # Set the random seed so things are predictable.

# Features are 5 random normal variables.
features = torch.randn((1, 5))
# True weights for our data, random normal variables again.
weights = torch.randn_like(features)
# and a true bias term.
bias = torch.randn((1, 1))

print("hello lol")

hello lol


In [11]:
activation(torch.sum(features*weights)+bias)

tensor([[0.1595]])

In [27]:
activation(torch.mm(features,weights.t())+bias)

tensor([[0.1595]])

In [28]:
### Generate some data.
torch.manual_seed(7)  # Set the random seed so things are predictable.

# Features are 3 random normal variables.
features = torch.randn((1, 3))

# Define the size of each layer in our network.
n_input = features.shape[1]  # Number of input units, must match number of input features.
n_hidden = 2  # Number of hidden units.
n_output = 1  # Number of output units.

# Weights for inputs to hidden layer.
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer.
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers.
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [31]:
activation(torch.mm(activation(torch.mm(features,W1)+B1),W2)+B2)

tensor([[0.3171]])

In [32]:
## Your solution

## Activation function
def activation(x):
    """Sigmoid activation function."""
    return 1 / (1 + torch.exp(-x))


### Neural network
def multi_layer_nw(input_units, hidden_units, output_units):
    """Create a multi-layer network with input, hidden, and output units."""
    torch.manual_seed(7)  # Set the random seed so things are predictable

    # Define the size of each layer in our network
    n_input = input_units  # Number of input units, must match number of input features
    n_hidden = hidden_units  # Number of hidden units
    n_output = output_units  # Number of output units

    # Weights for inputs to hidden layer
    w1 = torch.randn(n_input, n_hidden)
    # Weights for hidden layer to output layer
    w2 = torch.randn(n_hidden, n_output)

    # and bias terms for hidden and output layers
    b1 = torch.randn((1, n_hidden))
    b2 = torch.randn((1, n_output))

    return w1, w2, b1, b2


def calc_output(features, w1, w2, b1, b2):
    """Calculate the output of the network."""
    h = activation(torch.matmul(features, w1).add_(b1))
    return activation(torch.matmul(h, w2).add_(b2))


# Features are flattened batch input
features = torch.flatten(images, start_dim=1)
w1, w2, b1, b2 = multi_layer_nw(features.shape[1], 256, 10)

out = calc_output(features, w1, w2, b1, b2)  # output of your network, should have shape (64,10)

NameError: name 'images' is not defined

In [33]:
from torch import nn

In [37]:
class Networkex(nn.Module):
    
    def __init__(self) -> None:
        super().__init__()
    
        ## First hidden layer
        self.hidden1 = nn.linear(784,128)
    
        ## Second hidden layer
        self.hidden2 = nn.linear(128,64)
    
        self.output = nn.linear(64,10)
        
        # Defining sigmoid and softmax
        self.sigmoid = nn.Sigmoid()
        self.softmax = nn.Softmax(dim=1)
        self.relu = nn.ReLu()

    def forward(self,x):
        x = self.hidden1(x)
        x = self.relu(x)
        x = self.hidden2(x)
        x = self.relu(x)
        x = self.output(x)
        x = self.softmax(x)
        return(x)
        